config/routes.rb
Rails.application.routes.draw do
  resources :projects
  root to: 'home#index'

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  # TODO: Move validations to Project::CreateForm and Project::UpdateForm
  validates :name, presence: true

  # TODO: Remove callbacks
  before_save :check_plan

  def check_plan
    return if user.plan == 'custom'
    return if user.plan == 'free'     && user.projects.count < 3
    return if user.plan == 'business' && user.projects.count < 10
    return if user.plan == 'premium'  && user.projects.count < 100
    return if user.plan == 'custom'

    errors.add(:base, "Your #{user.plan} plan is over limited. Please increase it for creating more projects")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum plan: %i[free business premium custom]

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    # TODO: Refactor to query
    @projects = current_user.projects.all
  end

  def show
    # TODO: Refactor to policy
  end

  def new
    # TODO: Refactor to form
    @project = Project.new
  end

  def create
    # TODO: Refactor to form & policy
    @project = current_user.projects.new(project_params)

    save_project = -> {
      if @project.save
        redirect_to @project, notice: 'Project was successfully created.'
      else
        render :new
      end
    }

    if current_user.plan == 'free' && current_user.projects.count < 3
      save_project.call

    elsif current_user.plan == 'business' && current_user.projects.count < 10
      save_project.call

    elsif current_user.plan == 'premium' && current_user.projects.count < 100
      save_project.call

    elsif current_user.plan == 'custom'
      save_project.call

    else
      redirect_to projects_path, alert: "Your #{current_user.plan} plan is over limited. Please increase it for creating more projects"
    end
  end

  def update
    # TODO: Refactor to form
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :user_id)
  end
end

app/views/home/index.html.erb
<h1>Hello</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BadRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <nav>
      <%= link_to 'Projects', projects_path %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% new_project_link = link_to('New Project', new_project_path) %>

<% if current_user.plan == 'free' && current_user.projects.count < 3 %>
  <%= new_project_link %>

<% elsif current_user.plan == 'business' && current_user.projects.count < 10 %>
  <%= new_project_link %>

<% elsif current_user.plan == 'premium' && current_user.projects.count < 100 %>
  <%= new_project_link %>

<% elsif current_user.plan == 'custom' %>
  <%= new_project_link %>

<% else %>
  <%= "Your #{current_user.plan} plan is over limited. Please increase it for creating more projects" %>

<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user.email %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>